BotBuilderCommunity/botbuilder-community-dotnet

- libraries/Bot.Builder.Community.Middleware.AzureAdAuthentication/README.md
- libraries/Bot.Builder.Community.Middleware.BestMatch/README.md
- libraries/Bot.Builder.Community.Middleware.HandleActivityType/README.md
- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/README.md
- libraries/Bot.Builder.Community.Middleware.SpellCheck/README.md
- libraries/Bot.Builder.Community.Middleware.Typing/README.md
- libraries/Bot.Builder.Community.Recognizers.FuzzyRecognizer/README.md
Added the details as per the finalized format for README including the badges.
> Updated README.md for BestMatch Middleware

- Bot.Builder.Community.sln
- libraries/Bot.Builder.Community.Storage.Elasticsearch/Bot.Builder.Community.Storage.Elasticsearch.csproj
- libraries/Bot.Builder.Community.Storage.Elasticsearch/DocumentItem.cs
- libraries/Bot.Builder.Community.Storage.Elasticsearch/ElasticsearchStorage.cs
- libraries/Bot.Builder.Community.Storage.Elasticsearch/ElasticsearchStorageOptions.cs
- libraries/Bot.Builder.Community.Storage.Elasticsearch/README.md
- tests/Bot.Builder.Community.Storage.Tests/Bot.Builder.Community.Storage.Tests.csproj
- tests/Bot.Builder.Community.Storage.Tests/Elasticsearch_StorageTests.cs
- tests/Bot.Builder.Community.Storage.Tests/StorageBaseTests.cs
- tests/Bot.Builder.Community.Storage.Tests/elasticsearchstoragesettings.json
Elasticsearch based storage component for bots created using Microsoft Bot Framework.
> Elasticsearch storage component

- libraries/Bot.Builder.Community.Adapters.Alexa/AlexaContextExtensions.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/AlexaSchema.cs
Allow access to user name, email etc, along the lines of AlexaGetUserAddress.
> Add AlexaGetUserProfile

- README.md
- libraries/Bot.Builder.Community.Adapters.Google/README.md
Fixed broken images and corrected some typos. Also, added a little clarification which I experienced while reading it.
> Updated README.md

- libraries/Bot.Builder.Community.Adapters.Alexa/AlexaAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Integration/AspNet.Core/AlexaHttpAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Integration/AspNet.Core/AlexaRequestHandler.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Integration/AspNet.Core/ApplicationBuilderExtensions.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Integration/AspNet.Core/IAlexaHttpAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Middleware/AlexaIntentRequestToMessageActivityMiddleware.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/README.md
- libraries/Bot.Builder.Community.Adapters.Google/Bot.Builder.Community.Adapters.Google.csproj
- libraries/Bot.Builder.Community.Adapters.Google/GoogleAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.Core/ApplicationBuilderExtensions.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.Core/GoogleHttpAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.Core/GoogleRequestHandler.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.Core/IGoogleHttpAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.WebApi/GoogleHttpConfigurationExtensions.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/GoogleBotOptions.cs
- libraries/Bot.Builder.Community.Adapters.Google/README.md
Added MVC support for Alexa and Google adapters, allowing for endpoints for each to be surfaced via controllers within your project.
> Adapter mvc support

- samples/Google Adapter Sample/GoogleAdapterSampleBot.cs
Commented the audio sample code for explicit usage.
> Fixed #56 - Google Adapter Sample

- libraries/Bot.Builder.Community.Adapters.Alexa/AlexaAdapter.cs
…he readme but appears to have been removed at some point).
> Added support for Alexa Signin Card

- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/Bot.Builder.Community.Middleware.SentimentAnalysis.csproj
- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/SentimentExtensions.cs
Update Microsoft.Azure.CognitiveServices.Language.TextAnalytics package to v3.0
>  Update TextAnalytics package to v3.0

- Bot.Builder.Community.Samples.sln
- libraries/Bot.Builder.Community.Dialogs.Luis/README.md
- samples/Luis Dialog Sample/AdapterWithErrorHandler.cs
- samples/Luis Dialog Sample/Bots/DialogBot.cs
- samples/Luis Dialog Sample/Controllers/BotController.cs
- samples/Luis Dialog Sample/DialogExtensions.cs
- samples/Luis Dialog Sample/Dialogs/PromptWaterfallDialog.cs
- samples/Luis Dialog Sample/Dialogs/SimpleNoteDialog.cs
- samples/Luis Dialog Sample/Luis Dialog Sample.csproj
- samples/Luis Dialog Sample/Models/Note.cs
- samples/Luis Dialog Sample/Program.cs
- samples/Luis Dialog Sample/README.md
- samples/Luis Dialog Sample/Startup.cs
- samples/Luis Dialog Sample/appsettings.Development.json
- samples/Luis Dialog Sample/appsettings.json
- samples/Luis Dialog Sample/wwwroot/default.html
This is a migration of https://github.com/microsoft/BotFramework-Samples/tree/master/docs-samples/CSharp/Simple-LUIS-Notes-Sample/Simple-LUIS-Notes-Sample
> Add luis dialog sample

- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/Bot.Builder.Community.Middleware.SentimentAnalysis.csproj
- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/SentimentExtensions.cs
- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/SentimentMiddleware.cs
- samples/Sentiment Middleware Sample/Sentiment Middleware Sample.csproj
- samples/Sentiment Middleware Sample/Sentiment_Middleware_SampleBot.cs
- samples/Sentiment Middleware Sample/Startup.cs
Also, updated the relevant sample.
> Extended Sentiment Analysis Middleware with on-device Sentiment Analyzer

- libraries/Bot.Builder.Community.Adapters.Google/GoogleAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Google/GoogleRequestSchema.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.Core/ApplicationBuilderExtensions.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.Core/GoogleHttpAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.Core/SetGoogleUniqueRequestIdMiddleware.cs
- Google Request Schema update
- Added .NET Core middleware to create and add a unique ID for an incoming request to the HttpContext.  This can then be used as the ActivityId by the Google Adapter and may also be used by ITelemetryInitializers for gathering telemetry.
> Google Updates

- libraries/Bot.Builder.Community.Adapters.Alexa/Directives/Dialogs/DialogConfirmIntentDirective.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Directives/Dialogs/DialogConfirmSlotDirective.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Directives/Dialogs/DialogDelegateDirective.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Directives/Dialogs/DialogDirective.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Directives/Dialogs/DialogElicitSlotDirective.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Directives/Dialogs/DialogUpdateDynamicEntitiesDirective.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/Middleware/AlexaIntentRequestToMessageActivityMiddleware.cs
Currently if i have a mix of Intents, some with slots and some without, the ones without fall over.
> Allow for intents that have no slots associated & Added Dialog Support

- libraries/Bot.Builder.Community.Adapters.Twitter/Hosting/WebhookMiddleware.cs
Adds the channel id info to incoming activities for libraries that rely on this info.
#140
> Add ChannelId to incoming activities

- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/ApiKeyServiceClientCredentials.cs
- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/Bot.Builder.Community.Middleware.SentimentAnalysis.csproj
- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/SentimentExtensions.cs
- libraries/Bot.Builder.Community.Middleware.SentimentAnalysis/SentimentMiddleware.cs
Changes include:
1. Update of the SentimentAnalyzer Package
2. Cognitive Services Schema
3. Bot Builder 4.5
> Updated the Middleware with latest changes

- libraries/Bot.Builder.Community.Adapters.Alexa/AlexaSchema.cs
Adding classes for Geolocation support on Alexa Context response messages.
> Adding classes for Geolocation support

- libraries/Bot.Builder.Community.Adapters.Google/GoogleAdapter.cs
> Fix google adapter bug about SuggestedActions conversion

- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.Core/GoogleHttpAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Google/Integration/AspNet.WebApi/GoogleRequestHandler.cs
Fix for #123 - also updated in the new adapter preview already.
> Update Google Content Type

- libraries/Bot.Builder.Community.Adapters.Alexa/AlexaAdapter.cs
- libraries/Bot.Builder.Community.Adapters.Alexa/README.md
- libraries/Bot.Builder.Community.Adapters.Alexa/TurnContextEx.cs
Updates following code review from @johnataylor
* Moved the outgoing activities list into the turn context.
* Removed multiple activity processing policy and made method virtual to enable override.
* Improved concatenation logic, including <speak> tag check
* Moved the <speak> tag logic into a single location to address logic conflict
> Changes following code review

- libraries/Bot.Builder.Community.Adapters.Alexa/AlexaSchema.cs
This PR adds a `person` field to the `AlexaSystem` class to support voiceprint on Alexa devices. (note that there is a subtle distinction between `user` (who registered the skill on the device) and `person` (the voiceprint, i.e. who interacted with the skill).
Referencing the Amazon docs:  https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html#system-object
```
{
"version": "1.0",
"session": {
"new": true,
"sessionId": "amzn1.echo-api.session.[unique-value-here]",
"application": {
"applicationId": "amzn1.ask.skill.[unique-value-here]"
},
"attributes": {
"key": "string value"
},
"user": {
"userId": "amzn1.ask.account.[unique-value-here]",
"accessToken": "Atza|AAAAAAAA...",
"permissions": {
"consentToken": "ZZZZZZZ..."
}
}
},
"context": { …
```
> add voiceprint support for Alexa

- Bot.Builder.Community.Samples.sln
The project was missing from the solution so I have now added it as a part of solution.
> Added the Alexa Adapter Sample to the Solution

- libraries/Bot.Builder.Community.Adapters.Google/GoogleAdapter.cs
> Develop to Master

- libraries/Bot.Builder.Community.Dialogs.Location/LocationDialog.cs
> Fix exception when bot state is null and SkipFavourites is set

- libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs
- libraries/Bot.Builder.Community.Adapters.Alexa.Core/Helpers/AlexaMarkdownToPlaintextRenderer.cs
- libraries/Bot.Builder.Community.Adapters.Google.Core/Helpers/GoogleMarkdownToPlaintextRenderer.cs
- libraries/Bot.Builder.Community.Adapters.Google.Core/Helpers/MappingHelper.cs
- libraries/Bot.Builder.Community.Adapters.Google/GoogleAdapter.cs
- tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs
* Fix up activity merge to handle punctuation correctly
* Renamed ProcessOutgoingActivities to ProcessOutgoingActivitiesAsync and altered return type to be a Task
* Pass TurnContext into ProcessActivities
> Amendments following user feedback

- libraries/Bot.Builder.Community.Dialogs.Prompts/readme.md
> Nuget package link has updated

- libraries/Bot.Builder.Community.Adapters.MessageBird/Bot.Builder.Community.Adapters.MessageBird.csproj
Updated Bot.Builder.Community.Adapters.MessageBird.csproj file, added Description for NuGet package.
https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/343
> Updated Bot.Builder.Community.Adapters.MessageBird.csproj

- Bot.Builder.Community.sln
- libraries/Bot.Builder.Community.Components.Dialogs.Input/Bot.Builder.Community.Components.Dialogs.Input.csproj
- libraries/Bot.Builder.Community.Components.Dialogs.Input/DialogsInputBotComponent.cs
- libraries/Bot.Builder.Community.Components.Dialogs.Input/EmailInput.cs
- libraries/Bot.Builder.Community.Components.Dialogs.Input/PhoneNumberInput.cs
- libraries/Bot.Builder.Community.Components.Dialogs.Input/Schemas/BotBuilderCommunity.EmailInput.schema
- libraries/Bot.Builder.Community.Components.Dialogs.Input/Schemas/BotBuilderCommunity.EmailInput.uischema
- libraries/Bot.Builder.Community.Components.Dialogs.Input/Schemas/BotBuilderCommunity.PhoneNumberInput.schema
- libraries/Bot.Builder.Community.Components.Dialogs.Input/Schemas/BotBuilderCommunity.PhoneNumberInput.uischema
- libraries/Bot.Builder.Community.Components.Dialogs.Input/Schemas/BotBuilderCommunity.SocialMediaInput.schema
- libraries/Bot.Builder.Community.Components.Dialogs.Input/Schemas/BotBuilderCommunity.SocialMediaInput.uischema
- libraries/Bot.Builder.Community.Components.Dialogs.Input/SocialMediaInput.cs
> PR: [feature/packages -preview] A collection of custom input for Bot Composer Component

- libraries/Bot.Builder.Community.Components.TokenExchangeSkillHandler/Bot.Builder.Community.Components.TokenExchangeSkillHandler.csproj
Fixes: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/396
> Update TokenExchangeSkillHandler tags and package info

- Bot.Builder.Community.sln
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/BaseSettings/BaseMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/BaseSettings/IBaseMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Bot.Builder.Community.Components.Middleware.TextRecognizer.csproj
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Middleware/EmailRecognizerMiddleware.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Middleware/InternetTypeRecognizerMiddleware.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Middleware/PhoneNumberRecognizerMiddleware.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Middleware/SocialMediaRecognizerMiddleware.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/README.md
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/EmailMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/IEmailMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/IInternetProtocolMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/IPhoneNumberMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/ISocialMediaMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/InternetProtocolMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/InternetProtocolType.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/PhoneNumberMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/SocialMediaMiddlewareSettings.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/Settings/SocialMediaType.cs
- libraries/Bot.Builder.Community.Components.Middleware.TextRecognizer/TextRecognizerComponent.cs
> Added TextRecognizer middlware compoent

- libraries/Bot.Builder.Community.Components.Adapters.GoogleBusiness.Core/GoogleBusinessMessagingRequestMapper.cs
- libraries/Bot.Builder.Community.Components.Adapters.GoogleBusiness.Core/Model/GoogleEventType.cs
- libraries/Bot.Builder.Community.Components.Adapters.GoogleBusiness.Core/Model/OutgoingEvent.cs
- libraries/Bot.Builder.Community.Components.Adapters.GoogleBusiness.Core/Model/OutgoingMessage.cs
- Add google event types
- Add activity to google event support
> Add activity to google event for GoogleBusinessMessagingRequestMapper
