BotBuilderCommunity/botbuilder-community-dotnet

libraries/Bot.Builder.Community.Middleware.BestMatch/BestMatchMiddleware.cs

This middleware currently filters out all non message activities, need to call next if not a message activity.

Allow non messages through middleware

---

libraries/Bot.Builder.Community.Dialogs.FormFlow/FormDialog.cs

Fixes: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/51

Use Enum.ToObject when casting FormOptions

---

libraries/Bot.Builder.Community.Adapters.Twitter/ApplicationBuilderExtensions.cs
libraries/Bot.Builder.Community.Adapters.Twitter/Bot.Builder.Community.Adapters.Twitter.csproj
libraries/Bot.Builder.Community.Adapters.Twitter/Hosting/WebhookMiddleware.cs
libraries/Bot.Builder.Community.Adapters.Twitter/ServiceCollectionExtensions.cs
libraries/Bot.Builder.Community.Adapters.Twitter/TwitterAdapter.cs

Refactor some of the Twitter Adapter processing, to invoke bot pipeline and bring code patterns closer to other adapters.
Fixes #141

Process twitter adapter calls through middleware pipeline

---

libraries/Bot.Builder.Community.Dialogs.FormFlow/FormDialog.cs

This commit is fix to reset the form state on begindialog and it will fix [BotBuilderCommunity/botbuilder-community-dotnet] Formflow data gets recreated on successive calls (call to 2nd step) to form steps (#144)

Fix for resetting form state

---

libraries/Bot.Builder.Community.Adapters.Alexa/AlexaAdapter.cs

As the [BotFramework document ](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md) mentioned, the Timestamp of Activity should be in UTC.
Without the change, by default the Timestamp is local time.

Mark Activity.Timestamp as UTC

---

README.md
libraries/Bot.Builder.Community.Dialogs.Prompts/AdaptiveCardPrompt.cs
libraries/Bot.Builder.Community.Dialogs.Prompts/AdaptiveCardPromptResult.cs
libraries/Bot.Builder.Community.Dialogs.Prompts/AdaptiveCardPromptSettings.cs
libraries/Bot.Builder.Community.Dialogs.Prompts/AdaptiveCardPromptValidator.cs
libraries/Bot.Builder.Community.Dialogs.Prompts/AdaptiveCardPromptValidatorContext.cs
libraries/Bot.Builder.Community.Dialogs.Prompts/readme.md
tests/Bot.Builder.Community.Dialogs.Prompts.Tests/AdaptiveCardPromptTests.cs
tests/Bot.Builder.Community.Dialogs.Prompts.Tests/adaptiveCard.json

It was decided this should go in Community Repo rather than the SDK, but for reference see:
* [Original Dotnet PR](https://github.com/microsoft/botbuilder-dotnet/pull/3003)
* [Original Samples PR](https://github.com/microsoft/BotBuilder-Samples/pull/1986)
Note: There's a couple of classes that are sealed/protected/private in the BF SDK, so I had to copy/paste `PromptValidator` and `PromptValidatorContext` to get this to work.

Added AdaptiveCardPrompt

---

libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs
libraries/Bot.Builder.Community.Adapters.Alexa.Core/Utility/AttachmentUtility.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/Utility/AttachmentUtilityTests.cs

Convert the Alexa specific attachment content types to their correct type if needed.
If the type is one that we don't know about we ignore the conversion (leave the type as is) so other layers can take advantage of the attachment. If we are expected to convert the type but it is malformed we throw a ValidationException so the bot developer sees the error.
For most Adapter bots this will do nothing (it is a no-op). For code/bots that get the activity payload via json (ie invoking another bot or other) this will convert it to the right type.

Convert Alexa attachment types to their strong type if needed.

---

libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs
libraries/Bot.Builder.Community.Adapters.Alexa.Core/Attachments/Extensions.cs
libraries/Bot.Builder.Community.Adapters.Alexa.Core/Helpers/AttachmentHelper.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/AttachmentHelperTests.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/Bot.Builder.Community.Adapters.Alexa.Tests.csproj

Merge attachments in activities so they are available in the last message
Changed the Alexa activity content to be a JObject instead of the "native" Alexa type. The default Bot Builder serializer removes properties that don't have setters. The Type field on on the Cards only has a getter - so that property is dropped through serialization. There is a custom deserializer already on ICard which requires the Type field to deserialize (you get a null ref exception).
We should also push a change to the Alexa.NET repo to update their JsonConverter which may allow us to remove this code.

Merge attachments in activities so they are available in the last message

---

libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs
libraries/Bot.Builder.Community.Adapters.Alexa.Core/Helpers/AttachmentHelper.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/AttachmentHelperTests.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/Helpers/ActivityHelper.cs

Convert the Bot Framework attachment types to their strong type.
The type information for these gets lost when it, for example, goes through serialization. Added code to convert them to their strong type and some unit tests for validation.

Convert other attachments to their strong type

---

libraries/Bot.Builder.Community.Adapters.Alexa.Core/Helpers/AlexaMarkdownToPlaintextRenderer.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaMarkdownToPlaintextRendererTests.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs

This string 
"Same line.\nSame line.  \n2nd line.\n\r3rd line."
was being converted to 
"Same line.\nSame line.. 2nd line. 3rd line"
The \n in the middle should have been stripped out and the double .. before 2nd line should be removed.
This fixes it so it returns
"Same line. Same line. 2nd line. 3rd line."
and adds some tests.
Also quotes and links were not being rendered right. Quotes would be converted to &quot; and links would get repeated. Fixed and added tests.

Change Alexa md renderer to remove trailing periods. Added more tests.

---

libraries/Bot.Builder.Community.Dialogs.Prompts/readme.md

Somehow I missed this in the original PR, but this changes the README to use C# code and not JS for the AdaptiveCardPrompt sample code.

Convert to AdaptiveCardPrompt README example to C#

---

libraries/Bot.Builder.Community.Adapters.Alexa/Bot.Builder.Community.Adapters.Alexa.csproj
libraries/Bot.Builder.Community.Adapters.Google.Core/ConversationRequestMapper.cs
libraries/Bot.Builder.Community.Adapters.Google.Core/DialogFlowRequestMapper.cs
libraries/Bot.Builder.Community.Adapters.Google.Core/GoogleRequestMapperBase.cs
samples/Google Adapter Sample/Bots/EchoBot.cs
samples/Google Adapter Sample/Google Adapter Sample.csproj

- Updated logic for SuggestedActions to only convert IMBack and MesageBack CardActions into suggestion chips (as we can only use the text value and those action types map logically to suggestion chips).
- Added logic to look for a SuggestedAction with an action type of OpenUrl and if one exists, use the value to set the LinkOutSuggestion on the Google response.
- Remove unnecessary project referencefrom the Alexa project.

Updated Suggested Actions conversion logic 

---

libraries/Bot.Builder.Community.Adapters.Google.Core/Model/Request/ConversationWebhookRequestSchema.cs

This PR adds the `Device` object to `ConversationRequest` required to support Google location services (`DEVICE_PRECISE_LOCATION` permission).
https://developers.google.com/assistant/conversational/df-asdk/reference/webhook/rest/Shared.Types/AppRequest#Device
https://developers.google.com/assistant/conversational/df-asdk/helpers
1. Create a basic bot connected to a Google Action (**Important note:** that this will not work on Family Friendly Actions as it uses PII so disable that in Google Actions console) and send a permission request to Google e.g.:
```
var reply = turnContext.Activity.CreateReply();
var systemIntentAttachment = new PermissionsIntent()
{
InputValueData = new PermissionsInputValueData()
{
Type = "type.googleapis.com/google.actions.v2.PermissionValueSpec",
OptContext = …
```

add device to google request schema

---

libraries/Bot.Builder.Community.Adapters.Alexa.Core/AlexaRequestMapper.cs
tests/Bot.Builder.Community.Adapters.Alexa.Tests/AlexaRequestMapperTests.cs

There is a minor issue with the Alexa adapter mapping the skill request's locale through only for message activities (and not for other activity types e.g. conversation updates) - detailed in issue https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/issues/277
This fix is a small change to always map the `skillRequest.Request.Locale`. If there is a value, we get it.
Run the unit tests and ensure that all complete successfully. This PR adds four new unit tests:

map locale for all alexa requests

---

libraries/Bot.Builder.Community.Adapters.Google.Core/GoogleRequestMapperBase.cs

This adds support for mapping a bot framework hero card to google basic card
The code is pretty small and I have added conditions to deal with constraints that Google places on the basic card, namely:
- The basic card can only have [one button attached](https://actions-on-google.github.io/actions-on-google-nodejs/classes/conversation_response.basiccard.html#buttons)
- The button, if present must be an [`openUrl` and have a http or https URL](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/actionssdk_api_v2.googleactionsv2uielementsopenurlaction.html#url)
- The image, if present [should have accessible text](https://actions-on-google.github.io/actions-on-google-nodejs/interfaces/actionssdk_api_v2.googleactionsv2uielementsimage.html#accessibilitytext), if it is not …

add google hero card mapping

---

libraries/Bot.Builder.Community.Adapters.ActionsSDK/README.md

It looks like this readme was originally written with the project in Isolation instead of being consolidated into a much larger Repository. Since it now is part of a HUGE repo its not perhaps as self evident that the user is actually expected to download the whole thing and then find the action folder that is in the same directory as this readme in the resulting code base.
At least it wasn't obvious to me and cost me some time. Update hopefully will help the next guy.

Updated [Configure your Actions SDK project]

---

Bot.Builder.Community.sln
libraries/Bot.Builder.Community.Components.LanguageGeneration/Bot.Builder.Community.Components.LanguageGeneration.csproj
libraries/Bot.Builder.Community.Components.LanguageGeneration/EvaluateLGTemplate.cs
libraries/Bot.Builder.Community.Components.LanguageGeneration/LanguageGenerationBotComponent.cs
libraries/Bot.Builder.Community.Components.LanguageGeneration/LanguageGenerationComponentRegistration.cs
libraries/Bot.Builder.Community.Components.LanguageGeneration/Schemas/BotBuilderCommunity.EvaluateLGTemplate.schema
libraries/Bot.Builder.Community.Components.LanguageGeneration/Schemas/BotBuilderCommunity.EvaluateLGTemplate.uischema

This adds a new `Bot.Builder.Community.Components.LanguageGeneration` package which adds new action(s) for working directly with LG.  It initially contains a single `EvaluateLGTemplate` action for calling an LG template within the context of a dialog and saving the results to memory versus sending them as a response.  I have some ideas for more actions which will be added later.
I've tested it but still need to write the docs which I'll add shortly via another PR.

New LG components for manually evaluating an LG template

---

libraries/Bot.Builder.Community.Components.Handoff.ServiceNow/Bot.Builder.Community.Components.Handoff.ServiceNow.csproj
libraries/Bot.Builder.Community.Components.Handoff.ServiceNow/Converters/ObjectOrStringConverter.cs
libraries/Bot.Builder.Community.Components.Handoff.ServiceNow/Models/Body.cs
libraries/Bot.Builder.Community.Components.Handoff.ServiceNow/README.MD
libraries/Bot.Builder.Community.Components.Handoff.ServiceNow/ServiceNowController.cs
libraries/Bot.Builder.Community.Components.Handoff.ServiceNow/ServiceNowHandoffMiddleware.cs
libraries/Bot.Builder.Community.Components.Handoff.Shared/HandoffMiddleware.cs

- Ensure handoff events handled by the handoff middleware are swallowed and not passed to the user. 
- Update ServiceNow controller / middleware to handle datetimepicker. 
- Update readme.

Swallow handoff events and suppport datetime

---

libraries/Bot.Builder.Community.Components.Handoff.ServiceNow/ServiceNowController.cs

Ticket details including Short description & Additional Comments are getting truncating and not wrapping.
Please the below image where Additional Comments fields is getting truncated.
In this pull request wrap parameter is added for the Field Values for UI Type OutputCard in ServiceNowHandoffController class.
Thanks Palanikumar.

ServiceNow Handoff - Fix for Ticket Details are truncating and not wrapping

---

libraries/Bot.Builder.Community.Components.TokenExchangeSkillHandler/readme.md

Demonstrate the settingsPrefix for Bot.Builder.Community.Components.TokenExchangeSkillHandler in the root, not at the same level as components

Update token exchange skill handler readme

---

Bot.Builder.Community.Samples.sln
libraries/Bot.Builder.Community.Adapters.MessageBird/Bot.Builder.Community.Adapters.MessageBird.csproj
libraries/Bot.Builder.Community.Adapters.MessageBird/MessageBirdAdapter.cs
libraries/Bot.Builder.Community.Adapters.MessageBird/MessageBirdAdapterOptions.cs
libraries/Bot.Builder.Community.Adapters.MessageBird/MessageBirdRequestAuthorization.cs
libraries/Bot.Builder.Community.Adapters.MessageBird/Models/MessageBirdWebhookPayload.cs
libraries/Bot.Builder.Community.Adapters.MessageBird/README.md
libraries/Bot.Builder.Community.Adapters.MessageBird/ToActivityConverter.cs
libraries/Bot.Builder.Community.Adapters.MessageBird/ToMessageBirdConverter.cs
libraries/Bot.Builder.Community.Components.Adapters.MessageBird/Schemas/BotBuilderCommunity.MessageBirdAdapter.schema
libraries/Bot.Builder.Community.Components.Adapters.MessageBird/Schemas/BotBuilderCommunity.MessageBirdAdapter.uischema
samples/MessageBird Adapter Sample/Bots/EchoBot.cs
samples/MessageBird Adapter Sample/appsettings.json

issue #466
This update adds the new and suggested way of request verification with MessageBird API.
MessageBird NuGet package is updated to the version 3.2.0
Removed old request verification method and replaced it with new request verification method.
Required code for WhatsApp sticker messages has been added but commented because MessageBird Nuget package 3.2.0 does not support it yet, my PR is waiting to be reviewed and when it is merged, i'll uncomment and update the adapter code.
See : https://github.com/messagebird/csharp-rest-api/pull/111
Breaking Changes:
MessageBirdUseWhatsAppSandbox parameter is removed due to the changes in MessageBird C# NuGet package. This is no longer needed according to MessageBird. See https://github.com/messagebird/csharp-rest-api/pull/87
`public string …

MessageBird API New Request Verification Method and Breaking Changes

---

libraries/Bot.Builder.Community.Adapters.Webex/WebexClientWrapper.cs

Hi guys,
I'm currently trying the integration of the Webex adapter in a new bot project. I noticed a difference in the display between normal messages and the adaptive cards. Specifically, for me, it was the representation of German special characters (ä, ö, ü, ß) as well as emojis. After a long search and manual queries against the Webex API, I noticed the explicit ASCII encoding. This is only used by the adapter for messages with attachments. I suggest changing the encoding to UTF-8 and explicitly specifying the type in the HTTP header.
The tests all run through, however, this particular case does not appear to be under test (yet). I have applied the changes in my own deployment and the adaptive cards are now rendering correctly in Webex.
Best Regards,
Bastian
P.S. This is my first …

Webex Adapter: Changing encoding from ASCII to UTF8 to support extended charset

---

libraries/Bot.Builder.Community.Adapters.MessageBird/ToActivityConverter.cs
libraries/Bot.Builder.Community.Adapters.MessageBird/ToMessageBirdConverter.cs

Library joins channel name and channel id with - character when a webhook request comes and split and use that value for sending messages back. For channel names contains - character, bot does not respond. I changed the character to split to # so this won't be an issue after update.
This PR should be released as soon as we can because this is a show stopper for the people who has channel id's with - character.

Issue with channel id's that contains - character

---

libraries/Bot.Builder.Community.Adapters.Webex/Bot.Builder.Community.Adapters.Webex.csproj
libraries/Bot.Builder.Community.Adapters.Webex/WebexAdapter.cs
libraries/Bot.Builder.Community.Adapters.Webex/WebexClientWrapper.cs

This PR addresses an issue regarding Markdown-formatted messages with the Webex adapter #479. The current implementation calls the Webex API to create messages and supplies the content always under `text` which will result in a plain text message. However, we can call the same method and use `markdown` to supply a formatted message. In this case, we can additionally provide a plain text message for clients that are not able to render Markdown utilizing [`MarkdownToPlaintextRenderer`](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/cccc14f6f598f7ddf493ebbe42e4ba40126d19fd/libraries/Bot.Builder.Community.Adapters.Shared/MarkdownToPlaintextRenderer.cs#L10) (see also [API documentation](https://developer.webex.com/docs/api/v1/messages/create-a-message))
Moreover, I …

Webex Adapter: Adding support for Markdown and set default text format to Markdown instead of plain text
